.travis.yml

Part of #9 
Framework validation tests, which take much longer, are run separately from the core test suites.

Add travis config for Linux

---

tests/NodeApiTest.php

A couple of references hadn't been updated after removing the Node::kind property
close #26

Fix Node API test failures

---

src/Node.php
tests/NodeApiTest.php
tests/ParserInvariantsTest.php

This required some adjustment to remove the dependence on specific keys, in particular checks for $idx=0 and use of iterator_to_array() with $use_keys=true.
See also discussion in #23.

Use "yield from" in descendant generators

---

.gitignore

- this makes it easier to dogfood the syntax visualizer from this project

Ignore *.ast files in .gitignore

---

src/Node/Expression/TemplateExpression.php

_TemplateExpression_ cannot work as it is since it tries to extend the class _Node_ which doesn't exist in the same namespace.
It should extend _Expression_ like all the others classes in the same namespace.

TemplateExpression should extend Expression

---

.travis.yml

this makes the travis build break when syntax errors are contained in *.php files.
to prevent errors like https://github.com/Microsoft/tolerant-php-parser/pull/62

lint php files on travis builds

---

src/Lexer.php

For the given code:
```php
<?php
use Microsoft\PhpParser\Lexer;
$content = '<?php echo PHP_EOL;';
$lexer = new Lexer($content);
$tokens = $lexer->getTokensArray();
```
I got the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Microsoft\PhpParser\Token::getTextForToken() in src/Lexer.php:217
```
Since this class is not used anymore I'm wondering if it should even be kept in the code base.

fix fatal error from Lexer

---

tests/ParserGrammarTest.php

...by populating the .tree file with the test file contents, and running `git add`

Make it easier to set up new parser grammar tests

---

src/Node.php

This PR adds a missing predicate pass down the recursive `getDescendantNodes()` call. That also makes the method consistent with the `getDescendantTokens()` companion.

getDescendantNodes: pass predicate recursively

---

syntax-visualizer/client/README.md

This is typical of instructions for building VS Code extensions, so it seems helpful enough to me.

Fix #17 - syntax-visualizer instructions

---

src/Token.php

There was a little bottleneck, because once we found it, we iterated through others without any sense.

break when token was found

---

tests/LexicalGrammarTest.php

Make LexicalGrammarTest match ParserGrammarTest when a new test file is added

Fix LexicalGrammarTest when no expected tokens present

---

src/PhpTokenizer.php

This is no longer allowed in PHP 7.2, and is typically unwanted.
See https://wiki.php.net/rfc/counting_non_countables

Fix use of count() on a string value

---

src/ClassLike.php
src/Node/Statement/ClassDeclaration.php
src/Node/Statement/InterfaceDeclaration.php
src/Node/Statement/TraitDeclaration.php

Introduced ClassLike Interface

---

src/Node.php
src/Node/Expression/EchoExpression.php
src/Node/NumericLiteral.php
src/Node/QualifiedName.php
src/Node/ReservedWord.php
src/Node/StringLiteral.php

- Some node subclasses have `Token` (not an array) as `$this->children`
- Undefined variable in coalesce
- be more specific about getRoot()'s expected value.
- use string ...$classNames (same syntax as a real signature)
https://github.com/phpDocumentor/fig-standards/pull/87#r37054459
- EchoExpression has ExpressionList (no expressions would be invalid PHP)
- One form of string literal can be a single token, others (e.g. `"something $varName"` may have multiple tokens and expressions)

Make phpdoc of Node and its subclasses more accurate

---

src/Parser.php

Clarify phpdoc of parseDelimitedList
Don't assign a DelimitedList to node->nameParts,
it's declared as an array.
(Has no side effects, this is overwritten afterwards unless nameParts was null)

Fix incorrect PHPdoc for src/Parser.php, nit on property assignment

---

src/Token.php

The parameter isn't being modified, so having this is unexpected,
and passing params by reference is slower than passing by value.
The reference was part of the initial commit for src/Token.php

Remove an unnecessary reference from parameter.

---

tests/ParserFrameworkValidationTests.php

Noticed test failures for pgsql.phpunit.xml in the drupal project's test
files. (contains the substring ".php").
That also included `foo.php.gz`
Also, do the matching on the path name, not on the object to string
conversion.

Stop including non-php files in validation tests.

---

src/Token.php

Grammar test suite sped up from 1.2 seconds to 1.1 seconds.
This went from O(n) (loop over (around half of) 183 constants) to O(1) (hash lookup)

Speed up token value to name lookup

---

src/DiagnosticsProvider.php

This fixes two mistakes from my previous PR:
* `Node\Expression\NumericLiteral` ->`Node\NumericLiteral`
* All int tokens are `TokenKind::IntegerLiteralToken` regardles of numeric base
* Reworded message to stay consistent with missing token message

Fix breakout level literal parsing

---

README.md

When we now absolute path, it's better to use it

README: make require use of __DIR__

---

src/PhpTokenizer.php

Detected via static analysis
When there are duplicate array keys, the last entry takes precedence
(e.g. the removed T_EXIT line had the wrong value DieKeyword)

nit: Remove duplicate array keys

---

src/Parser.php

and a faster version of eatOptional().
eat() is called frequently when converting lexed tokens to values,
and often with a single token type. Varargs and array counting would
slow that down.
validatiion/ParserPerformance sped up from 0.581 to 0.574 seconds (1%).
(Added a loop to run on 100 files 10 times, divided by 10, took best times)
eatSingle might be a better name, but I'm not sure if this would get expanded to eatArray(array $x), eat2($kind1, $kind2), etc. It's private, so it can easily be changed.

Minor performance improvement: Add faster variant of eat()

---

tests/ParserGrammarTest.php
tests/api/getResolvedName.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertInstanceOf` instead of `instanceof` operator;
- `assertNotFalse` instead of comparison with `false` keyword.

Refactoring tests

---

experiments/BenchGetDiagnostics.php
src/DiagnosticsProvider.php
src/Node.php
src/Node/MethodDeclaration.php
src/Node/Statement/BreakOrContinueStatement.php
src/Node/Statement/NamespaceUseDeclaration.php

Add a simple benchmarking script
Extreme optimization, sacrificing code style in some areas.
- This is meant for discussion, since the project is
in the optimization phase. Avoiding nested generators did help performance.
This commit reduces the time needed to getDiagnostics
from 0.013 to 0.007 seconds. (On php 7.2.0RC5 with opcache enabled for CLI. Sample file was src/Token.php)
```
Average time to generate diagnostics (before): 0.013...
Average time to generate diagnostics (after):  0.006921
time to parse (Without diagnostics):           0.036374
```
(E.g. getDiagnostics previously took 36% of the time compared to generating an
AST, and now it takes 19% of that time.)

Optimize getDiagnostics for speed

---

src/Diagnostic.php
src/DiagnosticKind.php

E.g. if something using tolerant-php-parser is using DiagnosticKind,
but class diagnostic isn't loaded yet,
then I might fail to load this class.
(If the standard PSR-4 loading rules are used instead of an optimized autoloader)

Split DiagnosticKind out of Diagnostic.php

---

phpunit.xml

See https://phpunit.de/manual/current/en/risky-tests.html
I'm using php 7.2.2, and phpunit 6.5.6 gets installed.
I believe that the newer phpunit releases were stricter by default about
tests that don't perform any assertions

Don't emit "this test did not perform any assertions"

---

src/FilePositionMap.php
tests/FilePositionMapTest.php

Fixes #179, adds FilePositionMap
This assumes that requested offsets will be close to previous requests,
which should be true if this is used while walking a tree, etc.
Future tasks if the basic design is solid:
- copy license to new files
- Document this in the public API
- Deprecate PositionUtilities or make those APIs use FilePositionMap?
(E.g. cache FilePositionMap in a static variable,
and use $text is === as previous request)

Efficiently look up lines/columns of many nodes

---

src/FilePositionMap.php

I wasn't using some of those APIs for Node/Token,
and didn't notice the incorrect phpdoc/code.

Fix bugs and docs of FilePositionMap

---

docs/GettingStarted.md

The homebrew/php repository has been deprecated, and php formulae have been moved to [homebrew-core](https://github.com/Homebrew/homebrew-core)

Update Mac OS PHP installation instructions

---

src/Node.php

:wave: Doesn't seem possible that this method could return `null`.

Fixed docblock

---

src/Parser.php
src/PhpTokenizer.php

vendor/microsoft/tolerant-php-parser/src/Parser.php:1037 [2]
"continue" targeting switch is equivalent to "break".
Did you mean to use "continue 2"
Could you publish a 0.0.13 release for this? Phan's error handler deliberately terminates the program on PHP notices
See the note in https://github.com/php/php-src/blob/master/UPGRADING about "continue 2"

Fix notices seen in PHP 7.3.0alpha4 (but not alpha3)

---

src/Node/QualifiedName.php

This PR just fixes a single return type, but I just ran PHPStan on the code base and it picked up this and a multitude of other issues, so I might make a bigger PR addressing as many of those as possible.

Added missing string return type for QualfiedName#getResolvedName

---

.travis.yml
composer.json
phpstan.neon
src/Node.php
src/Node/Statement/NamespaceDefinition.php
src/Parser.php
src/PositionUtilities.php
src/Token.php

This PR introduces PHPStan and fixes the code up to level 2 (out of 7).
There remain 84 errors at `--level=7` (there were 117 before this PR)
--
PHPStan is `>=7.1` only, in `.travis.yml` it (should be) configured to run only on the 7.2 build.

RFC: Static analysis fixes

---

src/Parser.php
tests/cases/parser/scopedPropertyAccessExpression22.php
tests/cases/parser/scopedPropertyAccessExpression22.php.diag
tests/cases/parser/scopedPropertyAccessExpression22.php.tree

Fix a PHP notice generating a scoped property access expression

---

.travis.yml
phpstan.neon

With this patch, we can make the usage of PHPStan both locally and in our CI easier. Instead of figure out what paths and level we're using in the project, one can just do the following now:
```bash
$ composer require --dev phpstan/phpstan
$ vendor/bin/phpstan analyze
```

Move PHPStan configuration to its file

---

src/Node/QualifiedName.php

As we don't need the array index here, we can use the `in_array` function.

Use in_array instead of array_search + comparison

---

src/Token.php

Token->getText() will be called frequently in some applications.
This is slightly more efficient; the php interpreter can cache the address of the C function object when the namespace of the function is unambiguous.

Use fully qualified substr in Token.php

---

src/Node/DelimitedList.php
src/PhpTokenizer.php

When constants aren't fully qualified, the php interpreter has to check both the current namespace (Microsoft\TolerantPHPParser) and the global namespace for that constant. It does that every loop iteration (e.g. for every token in that file).
- When the constant is fully qualified, the php interpreter can replace the internal constant access with its integer value in the bytecode.
- Phan has a plugin that can detect uses of functions/constants that aren't fully qualified - see https://github.com/phan/phan/blob/master/.phan/plugins/NotFullyQualifiedUsagePlugin.php
Also, combine creating an array and appending to that array in DelimitedList, because it's used frequently (statement lists, argument lists, param lists, etc.)
Related to #15

Add micro-optimizations

---

phpstan.neon
src/PhpTokenizer.php

Speeds up parsing speed by a few percentage points.
- Move skipping prefix out of the loop.
It isn't used except when getting doc comments, which is much less
common than getting all tokens
- Handle strings separately from arrays in token_get_all.
- Move `if` within a switch to its own case.

Optimizations to PhpTokenizer

---

src/Parser.php
tests/cases/parser/binaryExpression20.php
tests/cases/parser/binaryExpression20.php.diag
tests/cases/parser/binaryExpression20.php.tree

Properly handle failure to parse right side of binary operations

---

tests/cases/parser/functions13.php

https://wiki.php.net/rfc/trailing_comma_in_parameter_list
is likely to pass, and makes that obsolete

Remove TODO for trailing comma in parameter list

---

docs/GettingStarted.md

- **Update composer instructions**
Fixes `Deprecation warning: require.Microsoft/tolerant-php-parser is invalid, 
it should not contain uppercase characters. Please use 
microsoft/tolerant-php-parser instead. Make sure you fix this as 
Composer 2.0 will error.`
- **GettingStarted: Update instructions to PHP 7.2**
PHP 7.1 is no longer supported, and the project targets PHP 7.2 
according to [.travis.yml](https://github.com/microsoft/tolerant-php-parser/blob/master/.travis.yml#L18)

docs/GettingStarted: Update instructions

---

src/Node/CatchClause.php
src/Parser.php
tests/cases/parser/tryStatement10.php.diag
tests/cases/parser/tryStatement10.php.tree
tests/cases/parser/tryStatement13.php.diag
tests/cases/parser/tryStatement13.php.tree
tests/cases/parser/tryStatement8.php.diag
tests/cases/parser/tryStatement8.php.tree
tests/cases/parser/tryStatement9.php.diag
tests/cases/parser/tryStatement9.php.tree

https://wiki.php.net/rfc/non-capturing_catches was merged into php
8.0-dev.

Support parsing php 8.0's non-capturing catch statement

---

src/Node/AnonymousFunctionUseClause.php
src/Parser.php
tests/cases/parser/anonymousFunctionCreationExpression11.php
tests/cases/parser/anonymousFunctionCreationExpression11.php.diag
tests/cases/parser/anonymousFunctionCreationExpression11.php.tree

Closures require 1 or more variables if there is a `use` clause.
```
php > function() use(){};
Parse error: syntax error, unexpected ')', expecting '&' or variable
(T_VARIABLE) in php shell code on line 1
```

Warn about missing use variable

---

src/Parser.php
src/PhpTokenizer.php

Currently, it's possible to do,
but would require a lot of code duplication and pinning to an exact
version of tolerant-php-parser, which discourages overriding the lexer.
I can think of the following use cases for this.
My main reason is to reuse token_get_all() elsewhere,
but being able to parse `T_FN` in php < 7.4 (for short arrow functions) is also convenient.
- Multiple applications needing to use the result of token_get_all
for the same file. If none of them modify the array,
it's much faster to reuse the same array than to create this. (benchmarking, the time savings aren't as large as I thought, but there might be some memory savings for reusing the strings in the array)
For example, Phan's language server mode will potentially use
tolerant-php-parser. In addition to that, it also …

Add a way to override the lexer in a Parser instance

---

.travis.yml

Whenever Travis provides a stable 8.0 label, that can be switched to.
Currently, though, that's not available. 8.0snapshot could not be
installed when I tried.

Start running tests in travis with nightly

---

src/Parser.php
tests/cases/parser80/attributes16.php.diag
tests/cases/parser80/attributes16.php.tree
tests/cases/parser80/attributes17.php.diag
tests/cases/parser80/attributes17.php.tree
tests/cases/parser80/attributes18.php.diag
tests/cases/parser80/attributes18.php.tree
tests/cases/parser80/attributes19.php.diag
tests/cases/parser80/attributes19.php.tree

Each attribute group must have 1 or more elements.
The same approach is used for closure use element lists.
php > #[] class X{}
Parse error: syntax error, unexpected token "]" in php shell code
on line 1

Warn about #[] attribute groups of 0 length

---

src/Parser.php
src/TokenKind.php
src/TokenStringMaps.php
tests/cases/parser74/arrowFunctionUnionTypes.php.tree

Hi,
This PR implements the feature suggested in #191 
There already was a tests using `iterable`, for now I reused it.
If you want a dedicated test that's not a problem, I will simply need a few information:
* Should I remove the `iterable` type from the current `arrowFunctionUnionTypes.php` test so that it will not be impacted by the changes ?
* Where should I put the new test ? `tests/cases/parser71/iterableType.php` ?
* Is the example provided in the issue enough or do you have something else in mind ?

[Feature] Support the php 7.1 iterable type hint as a unique token kind

---

composer.json
tests/CallbackTestListener.php
tests/LexicalGrammarTest.php
tests/ParserGrammarTest.php

Prepare for testing with PHP 8.0. This works well enough with `--ignore-platform-reqs`
An alternative would be to drop support for php 7.0
The call to parent::addFailure was a no-op.

Support testing with phpunit 7 as well

---

src/Node.php

Hopefully fixes #255.
Adds an additional initial check for the source file node, after which we start searching in the ancestors.

Error when calling getNamespaceDefinition on SourceFileNode

---

src/Parser.php
tests/LexicalGrammarTest.php
tests/ParserGrammarTest.php

https://wiki.php.net/rfc/deprecate_dynamic_properties
was approved and merged into php 8.2.
Dynamic (undeclared) properties will be forbidden without
`#[AllowDynamicProperties]` in the next major release (9.0).
A separate followup question would be whether to include
`#[AllowDynamicProperties]` on the Node class declaration
or to instead do something similar to nikic/php-parser and add a dedicated
attributes array property for any applications using this library to
track state on nodes.
(This isn't something I personally need, though. I haven't found any use cases in applications I've used before, largely because static analyzers I'm aware of use php-parser or php-ast for analysis.)
- https://github.com/microsoft/tolerant-php-parser/network/dependents?dependent_type=PACKAGE would be a …

Fix PHP 8.2 deprecation notices in tolerant-php-parser

---

src/Parser.php

Any expression can be used as of 8.0 without an unexpected syntax error.
In encapsulated strings,
`"${a->prop}"` is equivalent to `"{${(a->prop)}}"` in php 8.0 and a
syntax error in previous php versions.
(Get the property `prop` of the global constant `a` (constants can be
objects in php 8.1), then get the variable with the name equal to that
string)
Related to #230

Remove a TODO that no longer applies in php 8.0

---

tests/ParserFrameworkValidationTests.php

1. We're parsing thousands of files and there are many tokens per file.
The overhead of all the assert statements is noticeable.
Optimizing out the check (when they'd pass) speeds this up 3x from 90 seconds to 30 seconds - notably, function calls in php are slow, and phpunit has multiple levels of them
2. Don't write files only to unlink them later.
Instead, save the failed file only on test suite failure

Speed up running the framework validation test suite

---

src/Parser.php
tests/cases/parser/classBaseClause2.php.tree
tests/cases/parser/namespaceDefinition2.php.diag
tests/cases/parser/namespaceDefinition2.php.tree
tests/cases/parser/namespaceDefinition4.php.diag
tests/cases/parser/namespaceDefinition4.php.tree
tests/cases/parser/namespaceUseDeclaration33.php
tests/cases/parser/namespaceUseDeclaration33.php.diag
tests/cases/parser/namespaceUseDeclaration33.php.tree

And emit a diagnostic - these would be parse errors in php

Add MissingToken for missing QualifiedName

---

src/Node.php
src/Node/SourceFileNode.php

`Parser::parseSourceFile()` accepts a nullable string $uri. Avoid a potential type error

Change getUri return type to nullable string

---

src/Node.php

The `string` is the type of each argument.
The `...` indicates that it is an array of that type, like `function (string ...$classNames)` also would indicate. (for static analyzers parsing that 
(already done elsewhere, e.g. Parser::eat)
```php
/**
* Retrieve the current token, and check that it's of the expected TokenKind.
* If so, advance and return the token. Otherwise return a MissingToken for
* the expected token.
* @param int|int[] ...$kinds
* @return Token
*/
private function eat(...$kinds) {
$token = $this->token;
if (\is_array($kinds[0])) {
$kinds = $kinds[0];
}
foreach ($kinds as $kind) {// ...
```

Use PHPDoc `@param string ...$classNames`

---

src/NamespacedNameTrait.php

See #390  
This code depended on `name` being NULL but now it seems to be MissingToken cc @TysonAndre

Fix regression with getNamespacedName()

---

.gitattributes

Exclude these files/directories when publishing releases to composer. .github only contains files for GitHub workflows (CI) right now.

Exclude phpstan.neon and .github directories from packages

---

.travis.yml
composer.json
phpstan.neon
src/Node.php
src/Node/EnumCaseDeclaration.php
src/Node/Expression/AssignmentExpression.php
src/Node/Expression/BinaryExpression.php
src/Node/Expression/PrefixUpdateExpression.php
src/Node/Expression/SubscriptExpression.php
src/Node/Expression/UnaryExpression.php
src/Node/Expression/UnaryOpExpression.php
src/Node/FunctionReturnType.php
src/Node/MissingMemberDeclaration.php
src/Node/NamespaceUseClause.php
src/Node/Statement/InlineHtml.php
src/Node/Statement/NamespaceDefinition.php
src/Parser.php

:wave: in [Phpactor](https://github.com/phpactor/phpactor) one of the most common types of error is accessing a member on NULL on TP parser nodes. So I thought I'd try and increase the type coverage.
This PR:
- Updates PHPStan to level 3.
- Fixes type hints (avoiding refactoring code).
- Adds PHPStan as a dev dependency (it ships as a PHAR now, so no conflicts).
- Removes the overridden public `opeand` property on the children of `UnaryExpression`
As a follow up question is it worth ditching Travis and adding PHPStan to the `main` GHA workflow?
We should be able to get to PHPStan level 5 pretty easy (30 errors) but level 6 is 368 errors :sweat_smile:

PHPStan Level 3
