microsoft/tolerant-php-parser

.gitmodules
phpunit.xml

add drupal to validation tests

---

tests/ParserGrammarTest.php
tests/skipped.json

add failing grammar tests to skipped.json

---

src/Node.php
src/Node/SourceFileNode.php

Fixes #23 per last comment. I've also dropped some references while at it.

Optimize memory usage of tree traversal

---

src/Lexer.php
src/Node/DelimitedList.php
src/Utilities.php
syntax-visualizer/server/src/parse.php
tests/NodeApiTest.php
tests/ParserInvariantsTest.php

#40 replace instances of array_push with $array[]

---

src/Lexer.php

Looks like this was missed from commit 0d9c0f2e9aaaab07d7410d1e41582a7da9fc07e8

Remove scanNextToken args

---

src/Parser.php
tests/cases/parser/objectCreationExpression9.php
tests/cases/parser/objectCreationExpression9.php.tree

My attempt at resolving #30. I didn't add lots of tests since it seems the inheritance testing is covered by `classBaseClause*` tests, but I can add more testing if desired.
fix #30

Resolve issue #30

---

src/Node.php

See commit [a80f1685](https://github.com/Microsoft/tolerant-php-parser/commit/a80f168542bce22354dcf389739a86f4db8de3a2#diff-1bbc407d884b6ad13aec9bf50cf437b2)

the class Script has been renamed SourceFileNode

---

tests/cases/parser/objectCreationExpression11.php
tests/cases/parser/objectCreationExpression11.php.tree
tests/cases/parser/objectCreationExpression12.php
tests/cases/parser/objectCreationExpression12.php.tree

Add more tests for anonymous classes

---

src/Utilities.php

I've fixed the following error :
```
PHP Fatal error:  Uncaught Error: Call to undefined method Microsoft\PhpParser\Token::getEnd() in src/Utilities.php:58
```

fix fatal error from Utilities::getDiagnostics

---

src/DiagnosticsProvider.php
src/Node.php
src/Node/Statement/NamespaceDefinition.php
src/Parser.php
tests/NodeApiTest.php
tools/RenameNodeKindProperty.php

- getAncestor-> getFirstAncestor
- add doc comments
- add tests
- miscellaneous minor fixes

Update Node::getAncestor method

---

src/PositionUtilities.php

use strrpos() in getLineCharacterPositionFromPosition() as suggested in issue #71

---

phpunit.xml
src/TextEdit.php
tests/TextEditTest.php

- Not 100% complete yet, but it's a start.
- Note that because we don't have incremental parsing yet, the entire tree is invalidated and will need to be reparsed.
- This API is also intended to be used by some incoming tests.

Add API to apply text edits to a document

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
Contributing.md

add VS Code launch config, recommended extensions

---

tests/LexicalGrammarTest.php
tests/ParserGrammarTest.php

remove dependence on index while iterating through test cases

---

.travis.yml
src/Node/TraitSelectOrAliasClause.php
src/Parser.php
tests/cases/parser/traits21.php
tests/cases/parser/traits21.php.tree
tests/cases/parser/traits22.php
tests/cases/parser/traits22.php.tree
tests/cases/parser/traits23.php
tests/cases/parser/traits23.php.tree
tests/skipped.json

#98 trait select clauses do not properly detect start of fully qualified name elements

---

.travis.yml

Time has taught me cryptic constructs like this should be commented, if not for yourself, then for your peers. But probably also for your future self.

Added `set -e` comment.

---

src/Node/Parameter.php
src/Node/UseVariableName.php

Fix getName when name is empty - should return null, not false.

---

.vscode/settings.json

Prevent files from these folders from showing up in search.

Add support folders to search.exclude

---

README.md

Using html here messes up the links below for some reason.

Fix CoC formatting

---

src/FunctionLike.php
src/Node/Expression/AnonymousFunctionCreationExpression.php
src/Node/MethodDeclaration.php
src/Node/Statement/FunctionDeclaration.php

Closes Microsoft/tolerant-php-parser#162
It feels strange to create a file with the namespace beginning with `Microsoft`...

Add Functionlike interface

---

src/Node/StringLiteral.php

Do not use method as argument for pass by reference on Token

---

.gitattributes

This pull request [exclude even more non-essential](https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production/) files when installing this package in production.
Happy Hacktoberfest!

Exclude more non-essential files

---

src/Node/Statement/BreakOrContinueStatement.php
src/Parser.php

Add phpdoc for parsing expressions.

Fix resolution of phpdoc for BreakOrContinueStatement

---

composer.json
tests/LexicalGrammarTest.php
tests/ParserGrammarTest.php

As we support `PHP 7`, I've updated our suite of tests to `PHPUnit 6`.

Update to PHPUnit 6

---

src/Node/Expression/TernaryExpression.php
src/Parser.php
tests/cases/parser/ternaryExpressions3.php
tests/cases/parser/ternaryExpressions3.php.diag
tests/cases/parser/ternaryExpressions3.php.tree
tests/cases/parser/ternaryExpressions4.php
tests/cases/parser/ternaryExpressions4.php.diag
tests/cases/parser/ternaryExpressions4.php.tree

Fix a notice in Parser->parseTernaryExpression()

---

src/Token.php

This makes static analyzers of this code and code using it more
effective at catching bugs.

Annotate the types on Token

---

src/Parser.php

Detected with https://github.com/tysonandre/phantypocheck

nit: Fix a typo in a variable name

---

syntax-visualizer/example/foo.php.ast

Update example ast output to latest version's output

---

composer.json
phpstan.neon
src/DiagnosticsProvider.php
src/Node.php
src/Node/Expression/ArgumentExpression.php
src/Node/InterfaceBaseClause.php
src/Node/NamespaceUseGroupClause.php
src/Node/QualifiedName.php
src/Node/RelativeSpecifier.php
src/Node/Statement/NamespaceUseDeclaration.php
src/Node/StringLiteral.php
src/Parser.php
tests/unit/Node/StringLiteralTest.php

This PR:
- adds support for PHPStan Level 4
- fixes string literal parsing and adds a test for it  (fixes #397)

Phpstan level 4

---

src/Node/QualifiedName.php
tests/api/getResolvedName.php

Discussion in https://github.com/microsoft/tolerant-php-parser/issues/400

fix: Allow getResolvedName to resolve QualifiedName in TraitUseClause
